# Generated by Django 5.2.12 on 2026-03-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Параметры, если загрузки файла нет (например, период, фильтры)",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "task_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "В ожидании"),
                            ("PROCESSING", "Обработка"),
                            ("SUCCESS", "Успех"),
                            ("FAILED", "Ошибка"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "output_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/%d/",
                        verbose_name="Файл результата",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="files.uploadedfile",
                        verbose_name="Загруженный файл",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
